### ISSUE TITLE
partner with kevin x

### ISSUE THREAD

**Issue by Kevinncode** [Legacy-Foundation/forum#5]
we hit 1k also wtf this github dam  hot cool 

#NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6 #NOMEE6

**Comment by Kevinncode** [comment]
damm this is very serious

**Comment by falseopx** [comment]
kevin x garbo no thanks
